force-app/main/default/objects/Cost_Share__c/Cost_Share__c.object-meta.xml
<CustomObject>
    <label>Plan Cost Share</label>
    <nameField>
        <label>Cost Share Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Shares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cost_Share__c/fields/costShareType__c.field-meta.xml
<CustomField>
    <fullName>costShareType__c</fullName>
    <label>Cost Share Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Share_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/max__c.field-meta.xml
<CustomField>
    <fullName>max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/min__c.field-meta.xml
<CustomField>
    <fullName>min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Plan Cost Shares</relationshipLabel>
    <relationshipName>Cost_Shares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/planService__c.field-meta.xml
<CustomField>
    <fullName>planService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan Service</label>
    <referenceTo>Plan_Service__c</referenceTo>
    <relationshipName>Cost_Shares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/productService__c.field-meta.xml
<CustomField>
    <fullName>productService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Service</label>
    <referenceTo>Product_Services__c</referenceTo>
    <relationshipName>Cost_Shares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/selectedValue__c.field-meta.xml
<CustomField>
    <fullName>selectedValue__c</fullName>
    <label>Selected Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/acaPlan__c.field-meta.xml
<CustomField>
    <fullName>acaPlan__c</fullName>
    <label>ACA Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/applicableCoverageTiers__c.field-meta.xml
<CustomField>
    <fullName>applicableCoverageTiers__c</fullName>
    <label>Applicable Coverage Tiers</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApplicableCoverageTier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/approvalProcessRequired__c.field-meta.xml
<CustomField>
    <fullName>approvalProcessRequired__c</fullName>
    <label>Approval Process Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/chpReligiousIndicator__c.field-meta.xml
<CustomField>
    <fullName>chpReligiousIndicator__c</fullName>
    <label>CHP Religious Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/creditableCoverageType__c.field-meta.xml
<CustomField>
    <fullName>creditableCoverageType__c</fullName>
    <label>Creditable Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Creditable_Coverage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/depAgeMax__c.field-meta.xml
<CustomField>
    <fullName>depAgeMax__c</fullName>
    <label>Dependent Age Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/depAgeWhen__c.field-meta.xml
<CustomField>
    <fullName>depAgeWhen__c</fullName>
    <label>Dependent Age When</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/distributionChannels__c.field-meta.xml
<CustomField>
    <fullName>distributionChannels__c</fullName>
    <label>Distribution Channel</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DistributionChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/employerContribution__c.field-meta.xml
<CustomField>
    <fullName>employerContribution__c</fullName>
    <label>Employer Contribution</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>Effective End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/formularyName__c.field-meta.xml
<CustomField>
    <fullName>formularyName__c</fullName>
    <label>Formulary Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/fundingArrangements__c.field-meta.xml
<CustomField>
    <fullName>fundingArrangements__c</fullName>
    <label>Funding Arrangement</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Funding_Arrangement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/grandfatheredPlan__c.field-meta.xml
<CustomField>
    <fullName>grandfatheredPlan__c</fullName>
    <label>Grandfathered Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/grpSizeMax__c.field-meta.xml
<CustomField>
    <fullName>grpSizeMax__c</fullName>
    <label>Group Max Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Group_Min_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/grpSizeMin__c.field-meta.xml
<CustomField>
    <fullName>grpSizeMin__c</fullName>
    <label>Group Min Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Group_Min_Size</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/hixMetalLevel__c.field-meta.xml
<CustomField>
    <fullName>hixMetalLevel__c</fullName>
    <label>HIX Metal Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Catastrophic</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/hsaVendor__c.field-meta.xml
<CustomField>
    <fullName>hsaVendor__c</fullName>
    <label>HSA Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/isDeductibleAmountsCombinedOrSeparate__c.field-meta.xml
<CustomField>
    <fullName>isDeductibleAmountsCombinedOrSeparate__c</fullName>
    <label>Deductible Amounts Are</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Deductible_Amounts_Are</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/isGrandmothered__c.field-meta.xml
<CustomField>
    <fullName>isGrandmothered__c</fullName>
    <label>Grandmothered Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/isHighDeductiblePlan__c.field-meta.xml
<CustomField>
    <fullName>isHighDeductiblePlan__c</fullName>
    <label>High-Deductible Plan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/isIncludeCreditAmount__c.field-meta.xml
<CustomField>
    <fullName>isIncludeCreditAmount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Include Credit Amount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/isIncludeSecondaryMoop__c.field-meta.xml
<CustomField>
    <fullName>isIncludeSecondaryMoop__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Include Secondary Moop</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/marketingStatus__c.field-meta.xml
<CustomField>
    <fullName>marketingStatus__c</fullName>
    <label>Marketing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marketing_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/marketSegments__c.field-meta.xml
<CustomField>
    <fullName>marketSegments__c</fullName>
    <label>Market Segments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MarketSegment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/memberFundings__c.field-meta.xml
<CustomField>
    <fullName>memberFundings__c</fullName>
    <label>Member Fundings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Funding</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/minEssentialCoverage__c.field-meta.xml
<CustomField>
    <fullName>minEssentialCoverage__c</fullName>
    <label>Min Essential Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/minValueCoverage__c.field-meta.xml
<CustomField>
    <fullName>minValueCoverage__c</fullName>
    <label>Min Value Coverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/pcpRequired__c.field-meta.xml
<CustomField>
    <fullName>pcpRequired__c</fullName>
    <label>PCP Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/planCoverageExceptions__c.field-meta.xml
<CustomField>
    <fullName>planCoverageExceptions__c</fullName>
    <label>Plan Coverage Exceptions</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>with Implants</fullName>
            </value>
            <value>
                <fullName>with Orthodontia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Effective Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/udfplan_LegalEntity__c.field-meta.xml
<CustomField>
    <fullName>udfplan_LegalEntity__c</fullName>
    <label>Legal Entity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RelatedPlans__c/RelatedPlans__c.object-meta.xml
<CustomObject>
    <label>Related Plan</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Related Plans Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RelatedPlans__c/fields/Option__c.field-meta.xml
<CustomField>
    <fullName>Option__c</fullName>
    <label>Option</label>
    <referenceTo>Option__c</referenceTo>
    <relationshipLabel>Related Plans</relationshipLabel>
    <relationshipName>Related_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RelatedPlans__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Related Plans</relationshipLabel>
    <relationshipName>Related_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/ApplicableCoverageTier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Family Member</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Individual +1 (Spouse)</fullName>
    </customValue>
    <customValue>
        <fullName>Individual + Dependents</fullName>
    </customValue>
    <masterLabel>Applicable Coverage Tier</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Creditable_Coverage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MA Min Creditable Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare Part B Medical</fullName>
    </customValue>
    <customValue>
        <fullName>Medicare Part D Rx</fullName>
    </customValue>
    <masterLabel>Creditable Coverage</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Deductible_Amounts_Are.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Combined</fullName>
    </customValue>
    <customValue>
        <fullName>Seperate</fullName>
    </customValue>
    <masterLabel>Deductible Amounts Are</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/DistributionChannel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>MSP</fullName>
    </customValue>
    <customValue>
        <fullName>On</fullName>
    </customValue>
    <customValue>
        <fullName>Off</fullName>
    </customValue>
    <customValue>
        <fullName>Private Exchange</fullName>
    </customValue>
    <customValue>
        <fullName>Public Exchange</fullName>
    </customValue>
    <masterLabel>Distribution Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Funding_Arrangement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ASO</fullName>
    </customValue>
    <customValue>
        <fullName>Fully Insured</fullName>
    </customValue>
    <masterLabel>Funding Arrangement</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Group_Min_Size.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>0</fullName>
    </customValue>
    <customValue>
        <fullName>1</fullName>
    </customValue>
    <customValue>
        <fullName>50</fullName>
    </customValue>
    <customValue>
        <fullName>51</fullName>
    </customValue>
    <customValue>
        <fullName>100</fullName>
    </customValue>
    <customValue>
        <fullName>2000</fullName>
    </customValue>
    <customValue>
        <fullName>999999</fullName>
    </customValue>
    <masterLabel>Group Min Size</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Marketing_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Marketed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Marketed</fullName>
    </customValue>
    <customValue>
        <fullName>Not Marketed /Configured</fullName>
    </customValue>
    <customValue>
        <fullName>Renewing Only</fullName>
    </customValue>
    <masterLabel>Marketing Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MarketSegment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ABF</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>individual Over 65</fullName>
    </customValue>
    <customValue>
        <fullName>Individual Under 65</fullName>
    </customValue>
    <customValue>
        <fullName>Large Group</fullName>
    </customValue>
    <customValue>
        <fullName>Large Group- GRS</fullName>
    </customValue>
    <customValue>
        <fullName>MEWA</fullName>
    </customValue>
    <customValue>
        <fullName>Mid group</fullName>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>National Account</fullName>
    </customValue>
    <customValue>
        <fullName>Small Group</fullName>
    </customValue>
    <customValue>
        <fullName>Student</fullName>
    </customValue>
    <masterLabel>Market Segment</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Member_Funding.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HIA</fullName>
    </customValue>
    <customValue>
        <fullName>HIA Plus</fullName>
    </customValue>
    <customValue>
        <fullName>HIA Plus-DF</fullName>
    </customValue>
    <customValue>
        <fullName>HRA</fullName>
    </customValue>
    <customValue>
        <fullName>HRA-DF</fullName>
    </customValue>
    <customValue>
        <fullName>HSA</fullName>
    </customValue>
    <masterLabel>Member Funding</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PlanController.cls
/*========================================================================================================
* @author Venkat Vishal Reddy Nakka, Deloitte
* @date 27/11/2019
* @description:  Container class for Apex methods to be called from React Application 
Modification Log:
------------------------------------------------------------------------------------
Developer         Mod Number  Date        Description
------------------------------------------------------------------------------------
Vishal Nakka      M-001       27/11/20198  Initial version
==========================================================================================================*/
global class PlanController {
    
    /**
    * Method createOptions
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @param string of option and related plans
    * @description : This method returns Option Id
    *                
    */  
    @RemoteAction
    global  static string createOptions(string optionsString) {
        
        set<id> planIdset = new set<id>();
        list<RelatedPlans__c> relatedplans = new list<RelatedPlans__c>();
        
        JSONParser parser = JSON.createParser(optionsString);
        while (parser.nextToken() != null) {
            if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'option')) {                
                parser.nextToken();
                planIdset.add(parser.getIdValue());                
            }
        }

        system.debug('--planIdset--'+planIdset);
        
        Option__c opt = new Option__c();
        opt.Name='Option';
        insert opt;
        
        for(string planId:planIdset){
            RelatedPlans__c rp = new RelatedPlans__c();
            rp.Option__c=opt.Id;
            rp.Plan__c=planId;
            relatedplans.add(rp);
        }
        
        try{
            insert relatedplans;
        }Catch(Exception e){
            system.debug('--exception in option--'+e);
        }
       return opt.Id;
    }
    
     /**
    * Method getPlanList
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @param string of searchkeys
    * @description : This method returns list of Plans               
    */  
    @RemoteAction
    global  static list<object> getPlanList(string searchKey) {
        Set<String> planfieldNames = Plan__c.sObjectType.getDescribe().fields.getMap().keySet();
        Set<String> plancostSharefieldNames = Cost_Share__c.sObjectType.getDescribe().fields.getMap().keySet();        
        string costShareQueryString = 'select '+ string.join(new list<string>(plancostSharefieldNames), ',') + ' from Cost_Shares__r';
        string query_String = 'select ' + string.join(new list<string>(planfieldNames), ',') +',(' + costShareQueryString +')'+' from Plan__c';                                      
        return (list<object>) getFormatedPlans(Database.query(query_String));
    }
    
     /**
    * Method getPlansOnSearch
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @param string of JSON with Plan name, Plan type and related Cost Shares with Min,Max values 
    * @description : This method returns list of Plans based on serch criteria of Cost Shares                
    */ 
    @RemoteAction
    global  static list<object> getPlansOnSearch(string searchJsonString) {
        
        set<string> planIdSet = new set<string>();        
        set<string> csTypes = new set<string>();
        Set<String> planfieldNames = Plan__c.sObjectType.getDescribe().fields.getMap().keySet();
        Set<String> costSharefieldNames = Cost_Share__c.sObjectType.getDescribe().fields.getMap().keySet();
        string costShareQueryString = 'select '+ string.join(new list<string>(costSharefieldNames), ',') + ' from Cost_Shares__r';
        string queryString = 'select ' + string.join(new list<string>(planfieldNames), ',') +',(' + costShareQueryString +')'+' from Plan__c where ID IN:';
        list<JSON2Apex.CostShares> csWrapList = new list<JSON2Apex.CostShares>();
        
        JSON2Apex jsonWrap = JSON2Apex.parse(searchJsonString); 
        string planName = '\'%' + jsonWrap.planName  + '%\'';
        for(JSON2Apex.CostShares csj:jsonWrap.costShares){
            csTypes.add(csj.costShareType);
            csWrapList.add(csj);            
        }
        
        for(Cost_Share__c cs:[select id,Name,costShareType__c,plan__c,min__c,max__c,selectedValue__c from Cost_Share__c 
                              where costShareType__c IN:csTypes])
        {                
                for(JSON2Apex.CostShares csw:csWrapList){
                    integer min = csw.min!=null?csw.min:0;
                    integer max = csw.max!=null?csw.max:0;
                    if((csw.costShareType).equals(cs.costShareType__c) && (Integer.valueOf(cs.selectedValue__c)>=min && Integer.valueOf(cs.selectedValue__c)<=max))
                        planIdSet.add(cs.plan__c);                    
                }                                                          
        }
        
        queryString +='planIdSet OR Name Like '+planName ; 
        return (list<object>) getFormatedPlans(Database.query(queryString));
    }
    
   
    /**
    * Method getFormatedPlans
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @param List of Plan records 
    * @description : This method returns list of Plans formated as required by react app
    *                
    */
    public static list<Plan> getFormatedPlans(list<Plan__c> planList){
        
        list<Plan> newplanList = new list<Plan>();        
        for(Plan__c pl:planList){    
            Plan p = new Plan();
            p.name = pl.Name;
            p.id=pl.Id;
            p.acaPlan=pl.acaPlan__c;
            p.applicableCoverageTiers=pl.applicableCoverageTiers__c!=null ? (pl.applicableCoverageTiers__c).split(';'):null;
            p.approvalProcessRequired=pl.approvalProcessRequired__c;
            p.chpReligiousIndicator=pl.chpReligiousIndicator__c;
            p.creditableCoverageType=pl.creditableCoverageType__c;
            p.isDeductibleAmountsCombinedOrSeparate=pl.isDeductibleAmountsCombinedOrSeparate__c!=null ? (pl.isDeductibleAmountsCombinedOrSeparate__c).split(';'):null;
            p.depAgeMax=integer.valueOf(pl.depAgeMax__c);
            p.depAgeWhen=pl.depAgeWhen__c;
            p.distributionChannels=pl.distributionChannels__c!=null ? (pl.distributionChannels__c).split(';'):null;
            p.endDate=string.valueOf(pl.endDate__c);
            p.startDate=string.valueOf(pl.startDate__c);
            p.employerContribution=pl.employerContribution__c;
            p.formularyName=pl.formularyName__c;
            p.fundingArrangements=pl.fundingArrangements__c!=null?(pl.fundingArrangements__c).split(';'):null;
            p.grandfatheredPlan=pl.grandfatheredPlan__c;
            p.isGrandmothered=pl.isGrandmothered__c;
            p.grpSizeMax=pl.grpSizeMax__c;
            p.grpSizeMin=pl.grpSizeMin__c;
            p.isHighDeductiblePlan=pl.isHighDeductiblePlan__c;
            p.hixMetalLevel=pl.hixMetalLevel__c!=null?(pl.hixMetalLevel__c).split(';'):null;
            p.hsaVendor=pl.hsaVendor__c;
            p.isIncludeCreditAmount=pl.isIncludeCreditAmount__c;
            p.isIncludeSecondaryMoop=pl.isIncludeSecondaryMoop__c;
            p.legalEntity=pl.udfplan_LegalEntity__c;
            p.marketingStatus=pl.marketingStatus__c;
            p.marketSegments=pl.marketSegments__c!=null?(pl.marketSegments__c).split(';'):null;
            p.memberFundings=pl.memberFundings__c!=null?(pl.memberFundings__c).split(';'):null;
            p.minEssentialCoverage=pl.minEssentialCoverage__c;
            p.minValueCoverage=pl.minValueCoverage__c;
            p.pcpRequired=pl.pcpRequired__c;
            p.planCoverageExceptions=pl.planCoverageExceptions__c;
            p.planDesign=pl.planDesign__c;
            p.planDueDate=string.valueOf(pl.planDueDate__c);
            p.productRegulatoryApproval=pl.productRegulatoryApproval__c!=null?(pl.productRegulatoryApproval__c).split(';'):null;
            p.productRegulatoryDate=string.valueOf(pl.productRegulatoryDate__c);
            p.planType=pl.planType__c;
            p.planYear=pl.planYear__c;
            p.Product=pl.Product__c;
            p.productClasses=pl.productClasses__c;
            p.productFamilies=pl.productFamilies__c;
            p.productTypes=pl.productTypes__c!=null?(pl.productTypes__c).split(';'):null;
            p.providerNetworks=pl.providerNetworks__c;
            p.providerNetworkLink=pl.providerNetworkLink__c;
            p.providerNetworkPhoneNumber=pl.providerNetworkPhoneNumber__c;
            p.providerTier=pl.providerTierDisplayNames__c!=null?(pl.providerTierDisplayNames__c).split(';'):null;
            p.religionPlanIndicator=pl.religionPlanIndicator__c;
            p.salesStatus=pl.salesStatus__c;
            p.sbcHeaderName=pl.sbcHeaderName__c;
            p.state=pl.state__c;
            p.planCostShares = getFormatedCostShares(pl.Cost_Shares__r);            
            newplanList.add(p);
        }        
        return newplanList; 
    }
    
    
    /**
    * Method getFormatedPlans
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @param List of Plan records 
    * @description : This method returns list of Plans formated as required by react app
    *                
    */
    public static list<CostShare> getFormatedCostShares(list<Cost_Share__c> csList){
        list<CostShare> newCostShareList = new list<CostShare>();        
        for(Cost_Share__c cs:csList){ 
            CostShare c = new CostShare();
            c.id=cs.Id;
            c.costShareLevel=cs.costShareLevel__c;
            c.costShareType=cs.costShareType__c;
            c.costShareTypeDesc=cs.costShareTypeDesc__c;
            c.defaultValue=integer.valueOf(cs.default__c);
            c.fromValue=integer.valueOf(cs.from__c);
            c.intervalName=cs.intervalName__c;
            c.isRangeValidationEnforced=cs.isRangeValidationEnforced__c;
            c.isZeroAllowed=cs.isZeroAllowed__c;
            c.max=integer.valueOf(cs.max__c);
            c.min=integer.valueOf(cs.min__c);
            c.plan=cs.plan__c;
            c.planService=cs.planService__c;
            c.productService=cs.productService__c;
            c.providerTier=cs.providerTier__c;
            c.scale=integer.valueOf(cs.scale__c);
            c.selectedValue=integer.valueOf(cs.selectedValue__c);
            c.severityLevel=cs.severityLevel__c;
            c.step=integer.valueOf(cs.step__c);
            c.to=integer.valueOf(cs.to__c);
            c.format=cs.format__c;
            newCostShareList.add(c);
        }
        return newCostShareList;
    }
    /**
    * Class Plan
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @description : This is a wrapper class for holding plan records
    *                
    */
    public class Plan{
        public string name;
        public string id;
		public string acaPlan;
		public list<string> applicableCoverageTiers;
		public string approvalProcessRequired;
		public string chpReligiousIndicator;
		public string creditableCoverageType;
		public list<string> isDeductibleAmountsCombinedOrSeparate;
		public integer depAgeMax;
		public string depAgeWhen;
		public list<string> distributionChannels;
		public string endDate;
		public string startDate;
		public string employerContribution;
		public string formularyName;
		public list<string> fundingArrangements;
		public string grandfatheredPlan;
		public string isGrandmothered;
		public string grpSizeMax;
		public string grpSizeMin;
		public string isHighDeductiblePlan;
		public list<string> hixMetalLevel;
		public string hsaVendor;
		public boolean isIncludeCreditAmount;
		public boolean isIncludeSecondaryMoop;
		public string legalEntity;
		public string marketingStatus;
		public list<string> marketSegments;
		public list<string> memberFundings;
		public string minEssentialCoverage;
		public string minValueCoverage;
		public string pcpRequired;
		public string planCoverageExceptions;
		public string planDesign;
		public string planDueDate;
		public list<string> productRegulatoryApproval;
		public string productRegulatoryDate;
		public string planType;
		public string planYear;
		public string Product;
		public string productClasses;
		public string productFamilies;
		public list<string> productTypes;
		public string providerNetworks;
		public string providerNetworkLink;
		public string providerNetworkPhoneNumber;
		public string providerTierDisplayNames;
		public list<string> providerTier;
		public string religionPlanIndicator;
		public string salesStatus;
		public string sbcHeaderName;
		public string state;
        public list<CostShare> planCostShares;        
    }
    
    /**
    * Class CostShares
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @description : This is a wrapper class for Cost Shares sent from user search
    *                
    */
    public class CostShare{
        public string id;
        public string costShareLevel;
        public string costShareType;
        public string costShareTypeDesc;
        public integer defaultValue;
        public integer fromValue;
        public string  intervalName;
        public boolean isRangeValidationEnforced;
        public boolean isZeroAllowed;
        public integer max;
        public integer min;
        public string plan;
        public string planService;
        public string productService;
        public string providerTier;
        public integer scale;
        public integer selectedValue;
        public string severityLevel;
        public integer step;
        public integer to;
        public string format;
    }
    /**
    * Class CostShareWrap
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @description : This is a wrapper class for Cost Shares sent from user search
    *                
    */
    public class CostShareWrap{
        public string name;
        public integer min;
        public integer max;
    }
    
    /**
    * Class CostShareWrap
    * @author Venkat Vishal Reddy Nakka
    * @date 27/11/2019
    * @description : This is a wrapper class for Cost Shares sent from user search
    *                
    */
    public class PlanWrap{
        public string id;
        public integer min;
        public integer max;
    }
}