force-app/main/default/objects/Cost_Share__c/Cost_Share__c.object-meta.xml
<CustomObject>
    <label>Plan Cost Share</label>
    <nameField>
        <label>Cost Share Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Shares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cost_Share__c/fields/costShareLevel__c.field-meta.xml
<CustomField>
    <fullName>costShareLevel__c</fullName>
    <label>Cost Share Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CostShareLevels</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/costShareType__c.field-meta.xml
<CustomField>
    <fullName>costShareType__c</fullName>
    <label>Cost Share Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Share_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/costShareTypeDesc__c.field-meta.xml
<CustomField>
    <fullName>costShareTypeDesc__c</fullName>
    <label>Cost Share Type Desc</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Share_Type_Desc</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/default__c.field-meta.xml
<CustomField>
    <fullName>default__c</fullName>
    <label>Default</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/format__c.field-meta.xml
<CustomField>
    <fullName>format__c</fullName>
    <label>Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/from__c.field-meta.xml
<CustomField>
    <fullName>from__c</fullName>
    <label>From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/intervalName__c.field-meta.xml
<CustomField>
    <fullName>intervalName__c</fullName>
    <label>Interval Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Interval_Name</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/isRangeValidationEnforced__c.field-meta.xml
<CustomField>
    <fullName>isRangeValidationEnforced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Range Validation Enforced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/isZeroAllowed__c.field-meta.xml
<CustomField>
    <fullName>isZeroAllowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Zero Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/max__c.field-meta.xml
<CustomField>
    <fullName>max__c</fullName>
    <label>Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/min__c.field-meta.xml
<CustomField>
    <fullName>min__c</fullName>
    <label>Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Plan Cost Shares</relationshipLabel>
    <relationshipName>Cost_Shares</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/providerTier__c.field-meta.xml
<CustomField>
    <fullName>providerTier__c</fullName>
    <label>Provider Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provider_Tier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/scale__c.field-meta.xml
<CustomField>
    <fullName>scale__c</fullName>
    <label>Scale</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/selectedValue__c.field-meta.xml
<CustomField>
    <fullName>selectedValue__c</fullName>
    <label>Selected Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/severityLevel__c.field-meta.xml
<CustomField>
    <fullName>severityLevel__c</fullName>
    <label>Severity Level</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/step__c.field-meta.xml
<CustomField>
    <fullName>step__c</fullName>
    <label>Step</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Share__c/fields/to__c.field-meta.xml
<CustomField>
    <fullName>to__c</fullName>
    <label>To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/planExternalId__c.field-meta.xml
<CustomField>
    <fullName>planExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Plan External Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Cost_Share_Type_Desc.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Annual Maximum</fullName>
    </customValue>
    <customValue>
        <fullName>Basic</fullName>
    </customValue>
    <customValue>
        <fullName>Basic &amp; Major</fullName>
    </customValue>
    <customValue>
        <fullName>Carryover</fullName>
    </customValue>
    <customValue>
        <fullName>Diagnostic &amp; Preventive</fullName>
    </customValue>
    <customValue>
        <fullName>Endodontic Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Hospital Inpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Implants</fullName>
    </customValue>
    <customValue>
        <fullName>Initial Cost</fullName>
    </customValue>
    <customValue>
        <fullName>Level 1</fullName>
    </customValue>
    <customValue>
        <fullName>Level 2</fullName>
    </customValue>
    <customValue>
        <fullName>Level 3</fullName>
    </customValue>
    <customValue>
        <fullName>Lifetime</fullName>
    </customValue>
    <customValue>
        <fullName>Mail Order</fullName>
    </customValue>
    <customValue>
        <fullName>Major</fullName>
    </customValue>
    <customValue>
        <fullName>Mental Health Inpatient</fullName>
    </customValue>
    <customValue>
        <fullName>Orthodontia Lifetime</fullName>
    </customValue>
    <customValue>
        <fullName>Orthodontic</fullName>
    </customValue>
    <customValue>
        <fullName>Orthodontic Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Periodontic Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Retail</fullName>
    </customValue>
    <customValue>
        <fullName>Threshold</fullName>
    </customValue>
    <masterLabel>Cost Share Type Desc</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CostShareLevels.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Primary</fullName>
    </customValue>
    <customValue>
        <fullName>Secondary</fullName>
    </customValue>
    <customValue>
        <fullName>Tertiary</fullName>
    </customValue>
    <masterLabel>Cost Share Levels</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Interval_Name.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admission</fullName>
    </customValue>
    <customValue>
        <fullName>Benefit Period</fullName>
    </customValue>
    <customValue>
        <fullName>Day</fullName>
    </customValue>
    <customValue>
        <fullName>Episode</fullName>
    </customValue>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Lifetime</fullName>
    </customValue>
    <customValue>
        <fullName>Month</fullName>
    </customValue>
    <customValue>
        <fullName>No Limit</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Transplant</fullName>
    </customValue>
    <customValue>
        <fullName>Week</fullName>
    </customValue>
    <customValue>
        <fullName>Year</fullName>
    </customValue>
    <masterLabel>Interval Name</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Provider_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Network</fullName>
    </customValue>
    <customValue>
        <fullName>Out of Network</fullName>
    </customValue>
    <customValue>
        <fullName>Out of Area</fullName>
    </customValue>
    <customValue>
        <fullName>Out of Country</fullName>
    </customValue>
    <customValue>
        <fullName>Coverage</fullName>
    </customValue>
    <customValue>
        <fullName>Preferred Network 1</fullName>
    </customValue>
    <customValue>
        <fullName>Preferred Network 2</fullName>
    </customValue>
    <customValue>
        <fullName>Preferred Network 3</fullName>
    </customValue>
    <masterLabel>Provider Tier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreatePlanData.cls
public class CreatePlanData {
    
    
    public void CreatePlanData(){
        StaticResource sr = [SELECT Id,Name,Body,SystemModStamp
                             FROM StaticResource 
                             WHERE Name = 'PocData'
                             LIMIT 1];
        
        list<Plan__c> planInsertList = new list<Plan__c>();
        list<Cost_Share__c> csInsertList = new list<Cost_Share__c>();
        Map<String, Schema.SObjectField> planFieldMap =  Plan__c.sObjectType.getDescribe().fields.getMap();     
        Map<String, Object> fullDataMap = (Map<String, Object>) JSON.deserializeUntyped(sr.Body.toString());        
        Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(fullDataMap.get('response')));       
        list<Object> docList = (list<Object>) JSON.deserializeUntyped(JSON.serialize(responseMap.get('docs')));
        list<object> csList = new list<object>();
        
        
        
        for(Object ob:docList){
            
            Map<String, Object> recMap = (Map<String, Object>)ob;
            
            Plan__c p = new Plan__c();
            
            // Set default fields and values
            p.Name = (string) recMap.get('udfplan_enterprisePlnNme');
            p.planExternalId__c = (string) recMap.get('objectId');
            
            
            for(Schema.SObjectField fieldName:planFieldMap.values()){
                
                string fieldJson = string.valueOf(fieldName).removeEnd('__c');
                if(recMap.containsKey(fieldJson)){
                    
                    string fieldType =string.valueOf(fieldName.getDescribe().getType()); 
                    if(fieldType=='MULTIPICKLIST')
                    {                        
                        string pickListValues;
                        if(string.valueof(fieldName)=='providerTier__c')
                            pickListValues = string.valueOf(recMap.get('providerTierDisplayNames'));
                        else
                            pickListValues = string.valueOf(recMap.get(fieldJson));
                        
                        string multiSelectString;
                        for(string pi:pickListValues.split(',')){
                            multiSelectString = multiSelectString + pi +';';
                        }
                        
                        if(string.valueof(fieldName)=='providerTier__c')
                            p.put('providerTier__c',multiSelectString.removeEnd(';').remove('null').remove('(').remove(')'));
                        else
                            p.put(fieldName,multiSelectString.removeEnd(';').remove('null').remove('(').remove(')'));
                    }
                    else if(fieldType=='DOUBLE')
                        p.put(fieldName,(decimal) recMap.get(fieldJson));
                    else if(fieldType=='PICKLIST')
                    {
                        
                        if(recMap.get(fieldJson)==true)
                            p.put(fieldName,'Yes');
                        else if(recMap.get(fieldJson)==false)
                            p.put(fieldName,'No'); 
                        else if(fieldJson=='planYear' || fieldJson=='state' || fieldJson=='productClasses')
                            p.put(fieldName,((list<object>) recMap.get(fieldJson))[0]);                                         
                        else
                            p.put(fieldName,recMap.get(fieldJson));                                     
                        
                    }
                    else if(fieldType=='Date')
                    {  
                        list<string> dateList = string.valueOf(recMap.get(fieldJson)).split('T');
                        p.put(fieldName,Date.valueOf(dateList[0]));
                    }
                    else
                        p.put(fieldName,recMap.get(fieldJson));
                } 
            }
            
            planInsertList.add(p);
            
            csList.addAll((list<Object>) JSON.deserializeUntyped(JSON.serialize(recMap.get('planCostShares'))));
            
        }
        
        
        try{
            insert planInsertList;
        }Catch(Exception e){
            system.debug('--exception--'+e);
        }
        
        
        
        for(object csOb: csList){
            
            Map<String, Object> csMap = (Map<String, Object>)csOb;
            
            Cost_Share__c  cs = new Cost_Share__c ();
            cs.Name = (string) csMap.get('costShareType');
            cs.format__c = (string) csMap.get('format');
            cs.costShareLevel__c=string.valueOf(csMap.get('costShareLevel'));
            cs.costShareType__c=string.valueOf(csMap.get('costShareType'));
            cs.providerTier__c= string.valueOf(csMap.get('providerTier'))!='NA'? string.valueOf(csMap.get('providerTier')):'In Network';
            cs.costShareTypeDesc__c=string.valueOf(csMap.get('costShareTypeDesc'));
            cs.default__c=integer.valueOf(csMap.get('default'));
            cs.from__c=integer.valueOf(csMap.get('from'));
            cs.intervalName__c=string.valueOf(csMap.get('intervalName'));
            cs.isRangeValidationEnforced__c=false;
            cs.isZeroAllowed__c=true;
            cs.max__c=integer.valueOf(csMap.get('max'));
            cs.min__c=integer.valueOf(csMap.get('min'));
            cs.plan__r=new Plan__c(planExternalId__c = string.valueOf(csMap.get('parentId')));
            cs.scale__c=integer.valueOf(csMap.get('scale'));
            cs.selectedValue__c=integer.valueOf(csMap.get('selectedValue'));
            cs.severityLevel__c=(string) csMap.get('severityLevel');
            cs.step__c=integer.valueOf(csMap.get('step'));
            cs.to__c=integer.valueOf(csMap.get('to'));
            csInsertList.add(cs);
        }
        
        try{
            Database.insert(csInsertList,false);
        }Catch(Exception e){
            system.debug('--exception-in cs-'+e);
        }
        
        
        
    }
    
    
    
}